# Generated by Django 5.0.1 on 2024-01-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.IntegerField()),
                ('out', models.IntegerField()),
                ('fc', models.FloatField()),
                ('tf', models.FloatField()),
                ('ef', models.FloatField()),
                ('ar', models.FloatField()),
                ('ht', models.FloatField()),
                ('area', models.FloatField()),
            ],
        ),
    ]
